
image: openshift/origin-cli

stages:
  - build  # dummy stage to follow the template guidelines
  - test
  - deploy  # dummy stage to follow the template guidelines

variables:
  OPENSHIFT_SERVER: https://api.rm2.thpm.p1.openshiftapps.com:6443
  PROJECT_NAME: derbyve-dev
  BUILD_NAME: todo
  DEPLOYMENT_NAME: fastapi-app 
  NAMESPACE: derbyve-dev
  IMAGE_STREAM_TAG: frostylewin/myfastapiappv2:latest


before_script:
  - echo "$KUBECONFIG_CONTENT" > kubeconfig
  - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  - oc whoami

test:
  stage: test
  script: 
    - echo "Test started" && sleep 60s
    - echo "Test completed!"

build:
  stage: build
  script:
    - echo "Starting OpenShift build..."
    - oc start-build $BUILD_NAME --from-dir=. --follow -n $NAMESPACE
  only:
    - main


deploy:
  stage: deploy
  script:
    - echo "Deploying to OpenShift..."
    - oc rollout restart deployment/$DEPLOYMENT_NAME -n $NAMESPACE
  only:
    - main







