
image: openshift/origin-cli

stages:
  - build  # dummy stage to follow the template guidelines
  - deploy  # dummy stage to follow the template guidelines

variables:
  OPENSHIFT_SERVER: https://api.rm2.thpm.p1.openshiftapps.com:6443
  # Configure this variable in Secure Variables:
  OPENSHIFT_TOKEN: $OPENSHIFT_TOKEN
  PROJECT_NAME: derbyve-dev
  APP: fastapi-app

  


.deploy: &deploy
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
    - oc project "$PROJECT_NAME" 2> /dev/null 
  script:
    - "oc get services $APP 2> /dev/null || oc new-app . --name=$APP --strategy=docker"
    - "oc start-build $APP --from-dir=. --follow || sleep 3s && oc start-build $APP --from-dir=. --follow"
    - "oc get routes $APP 2> /dev/null








