stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$frostylewin" -p "$FrCLG0qgWs2iSw"
    - docker build -t $frostylewin/myfastapiappv2 .
    - docker push $frostylewin/myfastapiappv2:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG_CONTENT" | base64 -d > kubeconfig.yaml
    - export KUBECONFIG=$(pwd)/kubeconfig.yaml
    - kubectl set image deployment/fastapi-app =$IMAGE_TAG -n YOUR_NAMESPACE
  only:
    - main
